### ISSUE TITLE
Format of news

### ISSUE THREAD

**Issue by ghost** [dpw/pnntprss#1]
Hey,

Thank you for the program. It is very useful for reading RSS in Gnus. I am wondering is it possible to pre-format news. For example, right now the link to the article is shown by bold in the head of news. I would like to put this link in the end of  news (like in gwene). Also, i would like to format authors name and so on.. Could you help me in this? I am not very good in programming but i think i could do this if you tell me where to look.

**Comment by dpw** [comment]
Sorry I haven't responded more quickly.  I was on vacation and trying to keep away from computers.

It's should be possible to do what you suggest, and I'd be happy to do what I can to guide you through the process.

pnntprss constructs a simple HTML document for the body of the NNTP message created from a feed entry.  You can find the code that does this at https://github.com/dpw/pnntprss/blob/master/group.py#L334:
```
            res = "<h1><a href='%s'>%s</a></h1>\n%s" % (link, to_html(caption),
                                                                      res)
```
That just puts a `<h1>` header at the top of the message, linking to the URL for the post.  That's why you see a link at the top of each message. But you can change it to produce whatever HTML you want.  The post details are available in `self.entry`, which comes from the universal feed parser library (see the docs at https://pythonhosted.org/feedparser/, though sometimes experimentation is required to discover how UFP behaves for a wide range of feeds.

The `render_body` method is called inside the NNTP server part of pnntprss, so if you make a change there, you just need to restart that server to see the effect.

So for example, to add a line saying `Written by ...` to each message when we know its author, you would add this code before that above:
```
            author = self.author_name()
            if author:
                res = "<p>Written by %s<p>%s" % (cgi.escape(author), res)
```
where the `author_name` method is defined as:
```
    def author_name(self):
        for d in [self.entry, self.group.config]:
            if 'author_detail' in d:
                return d['author_detail']['name']
            elif 'author' in d:
                return d['author']
```

**Comment by ghost** [comment]
Thank you

**Comment by dpw** [comment]
I'm closing this for now, but you are welcome to open another issue if you have more questions.
